In [27]:
import torch
import torch.nn as nn


In [28]:
layer = nn.Conv2d(3,1,kernel_size=1,bias=False)
def init_weights(m):
    if type(m) == nn.Linear or type(m) == nn.Conv2d:
        m.weight = torch.nn.Parameter(torch.ones(m.weight.shape))
layer.apply(init_weights)

Conv2d(3, 1, kernel_size=(1, 1), stride=(1, 1), bias=False)

In [29]:
print(layer.state_dict())

OrderedDict([('weight', tensor([[[[1.]],

         [[1.]],

         [[1.]]]]))])


In [35]:
x = torch.ones((3,3,3))
y = layer(x)
print(y)
print(y.shape)
print(x.mean(dim=1))

tensor([[[3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.]]], grad_fn=<SqueezeBackward1>)
torch.Size([1, 3, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [41]:
x = torch.zeros((2,4,2,2))
x[0][1][1][1]=1
print(x)
print(x.mean((0,2,3)))

tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 1.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]])
tensor([0.0000, 0.1250, 0.0000, 0.0000])
