In [2]:
import torch
import torch.nn as nn

In [9]:
class Module(nn.Module):
    def __init__(self):
        super(Module,self).__init__()
        self.weight

    def forward(self,x):
        x = self.layers(x)
        return x

In [65]:
net = Module()

nn.init.zeros_(net.layers[0].weight)

x = torch.arange(12)
print(x)
torch.save(x,'x-file')

print(net.layers[0].weight.data)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[0., 0., 0., 0., 0., 0., 0., 0.]])


In [66]:
x = torch.load('x-file')
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
